language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t galanx/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true galanx/docker-react npm run test
